---
version: "2"    
services:       
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:    
      - /opt/homer/assets:/www/assets
    ports:      
      - 8080:8080
    restart: unless-stopped
                                  
